### ISSUE TITLE
UI/Font Size

### ISSUE THREAD

**Issue by Yanganof** [BepInEx/BepInEx.ConfigurationManager#33] opened 2021-06-29 20:54 UTC
Hello,
would it be possible to add an option to increase UI/Font Size?
I'm using 4k monitors, and it is very hard to read :(

Thanks

**Comment by ManlyMarco** [comment] 2021-06-30 04:06
Duplicate of #23
A custom GUIStyle is needed for this.

**Closed by ManlyMarco** 2021-06-30 04:06 UTC
