### ISSUE TITLE
Not all configs are showing up

### ISSUE THREAD

**Issue by deftesthawk** [BepInEx/BepInEx.ConfigurationManager#24] opened 2021-03-25 14:48 UTC
I have Valheim plus installed but it doesn't show the config options for that mod

**Comment by ghorsington** [comment] 2021-03-25 15:46
Greetings!

ConfigurationManager is a game-agnostic plugin and was meant for multiple games. As such, you would have to be more specific about what BepInEx version you're using and what plugin you're trying to edit the configs for.

If a plugin does not define any configuration values, nothing will be visible in ConfigurationManager.

All in all, please elaborate on your current setup and situation so that the situation can be better understood.

**Comment by ManlyMarco** [comment] 2021-04-03 03:10
Duplicate of #26

**Closed by ManlyMarco** 2021-04-03 03:10 UTC
