### ISSUE TITLE
Configuration Manager comes up but there is no text

### ISSUE THREAD

**Issue by hub2git** [BepInEx/BepInEx.ConfigurationManager#49] opened 2022-06-27 08:16 UTC
The Configuration manager comes up when I press F1, but there's no text. Please see these screenshots
![Screenshot from 2022-06-27 01-09-22](https://user-images.githubusercontent.com/7141051/175892096-100e8eec-5e80-4cd3-bbb8-2b2024086f73.png)
![Screenshot from 2022-06-27 01-09-28](https://user-images.githubusercontent.com/7141051/175892100-d70a9cfb-8b04-4512-a6db-fcf7b053f1ed.png)
![Screenshot from 2022-06-27 01-09-34](https://user-images.githubusercontent.com/7141051/175892103-a8010c89-db65-40b6-a005-1b56582e6fe8.png)
![Screenshot from 2022-06-27 01-09-39](https://user-images.githubusercontent.com/7141051/175892106-fa2df1e9-56a7-454b-bebc-1f7841294792.png)
![Screenshot from 2022-06-27 01-09-57](https://user-images.githubusercontent.com/7141051/175892111-e580b074-d16d-4fd1-89ad-e7883efbd5ff.png)

I'm running Linux Mint 20.3.
The game is Desperados 3 (windows version).
I got Bepinex (windows version) installed. I followed the instructions on https://docs.bepinex.dev/articles/advanced/steam_interop.html#protonwine, as suggested in my thread on https://github.com/BepInEx/BepInEx/issues/435. 
Running the mods from https://github.com/benediktwerner/Desperados3Mods

**Comment by ManlyMarco** [comment] 2022-07-16 17:50
Can you test the upcoming 17.1 release, and if it doesn't work check the output_log file in game for any exceptions that happen when the window is open?

**Comment by ManlyMarco** [comment] 2022-12-24 08:14
I couldn't reproduce the issue with latest version. If you still have the issue it's likely related to your system rather than the plugin (e.g. a missing font). Unfortunately I don't think I can help with that from inside this plugin so I'll close the issue.
![image](https://user-images.githubusercontent.com/39247311/209427343-ac474393-20a9-46bf-a698-dcf7770c94ae.png)

**Closed by ManlyMarco** 2022-12-24 08:14 UTC

**Comment by ShockedCoder** [comment] 2026-03-23 10:54
The fix for this is `winetricks corefonts`. Running this will install the required fonts for the Unity textboxes and such.
Remember to set the `WINEPREFIX` env var, if you're running it in a different prefix
