### ISSUE TITLE
GUI problem with 4K resolution

### ISSUE THREAD

**Issue by JoewAlabel** [BepInEx/BepInEx.ConfigurationManager#67] opened 2023-05-06 14:16 UTC
Hi!
I am playing the game in 4k resolution (3840 x 2160) and the GUI is too long and the text's fonts are too small, making very hard to read.

There are an ss of the problem:
![GUI texts too small](https://user-images.githubusercontent.com/69368385/236629402-fafb2809-d777-4124-a4ab-09facf57c8a1.jpg)

Is there a way to increases GUI fonts, buttons sizes and all others, please?
It is no problem with 1080p resolution, but with 4k it becomes too small to read.

Thanks!!!

**Comment by ManlyMarco** [comment] 2023-05-06 14:31
This looks to work as intended, currently the UI doesn't support scaling. Duplicate of #33, #23

**Closed by ManlyMarco** 2023-05-06 14:31 UTC

**Comment by JoewAlabel** [comment] 2023-05-13 13:28
I found a good solution for this problem:

1- Find the exe file of your game, and RMB click it.
2- Click at > **Properties**
3- Click at **Compatibility** tab.
4- Click the button: **Change high DPI settings**
5- Check (enable) the first option below Program DPI
6- Check (enable) the last option below High DPI scaling override
7- At this drop-down list, select > System

[Screen Shot](https://prnt.sc/6l2aqGW1-hcD)

**Comment by FrederickEngelhardt** [comment] 2023-11-14 09:33
@JoewAlabel This doesn't really fix the issue. This just forces the windows app to use a compatible DPI. That typically can be done by manually setting the resolution within the app. Example if you have a 4k screen it will drop DPI for all objects not just text to 1080p.
